export const projects = [
  {
    title: "David Teaches Code",
    description:
      "A personal coding tutorial and portfolio platform built with a modern frontend stack. Features smooth animations, responsive design, and showcases interactive projects with video previews. Designed to highlight teaching resources, projects, and technical writing in an engaging format.",
    tech: [
      "Next.js 13 App Router",
      "TypeScript",
      "Tailwind CSS",
      "Framer Motion",
      "React Hooks",
      "Server Components",
      "Vercel Deployment",
      "Responsive Design",
      "Lucide Icons",
    ],
    image: "/images/projects/project1.png",
    video: "/videos/david-teaches-code-preview.mp4",
    demo: "https://david-teaches-code.vercel.app/",
    github: "https://github.com/DavidZeff1/david-teaches-code",
  },
  {
    title: "PlacePal (Airbnb Clone)",
    description:
      "A full-stack property booking platform inspired by Airbnb. Supports property listings, user authentication, guest & date selection, secure payments, and responsive UI. Built to demonstrate real-world booking workflows with scalable architecture.",
    tech: [
      "React",
      "Next.js",
      "TypeScript",
      "Node.js",
      "Express-style API",
      "Postgres (Neon)",
      "Prisma ORM",
      "NextAuth Authentication",
      "Stripe Payments",
      "Cloudinary Image Uploads",
      "Tailwind CSS",
      "Vercel Deployment",
      "Responsive UI/UX",
      "Date Range Picker",
    ],
    image: "/images/projects/project1.png",
    video: "/videos/PlacePal.mp4",
    demo: "https://airbnb-83oc.vercel.app/",
    github: "https://github.com/DavidZeff1/airbnb",
  },
  {
    title: "David's Tech Reviews",
    description:
      "A tech review and blogging platform featuring MDX-based posts, affiliate integration, and AI-assisted content. Includes SEO optimization, structured data, and custom styling for product showcases. Built to explore content generation and monetization with Amazon Affiliates and OpenAI.",
    tech: [
      "Next.js 13 App Router",
      "TypeScript",
      "Tailwind CSS",
      "Prisma ORM",
      "MDX for Posts",
      "gray-matter",
      "OpenAI API Integration",
      "SEO Optimization",
      "Static Site Generation (SSG)",
      "Dynamic Metadata",
      "Affiliate Links (Amazon)",
      "Vercel Deployment",
    ],
    image: "/images/projects/project1.png",
    video: "/videos/DavidstechReviews.mp4",
    demo: "https://davidstechreviews.vercel.app/",
    github: "https://github.com/DavidZeff1/davidstechreviews",
  },
  {
    title: "Prisma Clone",
    description:
      "A clone of the official Prisma homepage, built to practice modern frontend development and design implementation. Focused on responsive layouts, interactive components, and smooth styling using Next.js, TypeScript, and Tailwind CSS. This project showcases the ability to replicate real-world production designs with clean, maintainable code.",
    tech: [
      "Next.js 13 App Router",
      "TypeScript",
      "Tailwind CSS",
      "Responsive Design",
      "Static Assets & Icons",
      "Vercel Deployment",
    ],
    image: "/images/projects/project1.png",
    video: "/videos/prisma-clone.mp4",
    demo: "https://prisma-clone-steel.vercel.app/",
    github: "https://github.com/DavidZeff1/prisma-clone",
  },

  {
    title: "Survivor Guy (Unity Game)",
    description:
      "A 2D survival game developed in Unity, where the player navigates waves of enemies and manages limited resources to stay alive. The project emphasizes clean architecture and the application of design pattern principles such as Singleton for game management, Observer for event handling, and Factory for spawning enemies. Built to strengthen game development skills with Unity while showcasing the ability to structure scalable and maintainable gameplay systems.",
    tech: [
      "Unity Engine",
      "C#",
      "2D Game Development",
      "Object-Oriented Programming (OOP)",
      "Design Patterns (Singleton, Observer, Factory)",
      "Game Loop Architecture",
      "Sprite & Asset Integration",
      "itch.io Deployment",
    ],
    image: "/images/projects/project1.png",
    video: "/videos/survivor-guy.mp4",
    demo: "https://gamerdave141592.itch.io/survivor-guy",
    github: "https://github.com/DavidZeff1/Final-Project",
  },
];
