export const projects = [
  {
    title: "David Teaches Code",
    description:
      "A portfolio website showcasing coding tutorials, projects, and technical articles. Features video previews, smooth animations, and a clean, modern design.",
    tech: [
      "Next.js 13 App Router",
      "TypeScript",
      "Tailwind CSS",
      "Framer Motion",
      "React Hooks",
      "Server Components",
      "Vercel Deployment",
      "Responsive Design",
      "Lucide Icons",
    ],
    image: "/images/projects/project1.png",
    video: "/videos/david-teaches-code-preview.mp4",
    demo: "https://david-teaches-code.vercel.app/",
    github: "https://github.com/DavidZeff1/david-teaches-code",
  },
  {
    title: "PlacePal (Airbnb Clone)",
    description:
      "A property rental platform where users can browse listings, book accommodations, and make secure payments. Includes user authentication and a responsive booking interface.",
    tech: [
      "React",
      "Next.js",
      "TypeScript",
      "Node.js",
      "Express-style API",
      "Postgres (Neon)",
      "Prisma ORM",
      "NextAuth Authentication",
      "Stripe Payments",
      "Cloudinary Image Uploads",
      "Tailwind CSS",
      "Vercel Deployment",
      "Responsive UI/UX",
      "Date Range Picker",
    ],
    image: "/images/projects/project1.png",
    video: "/videos/PlacePal.mp4",
    demo: "https://airbnb-83oc.vercel.app/",
    github: "https://github.com/DavidZeff1/airbnb",
  },
  {
    title: "David's Tech Reviews",
    description:
      "A tech blog featuring product reviews and articles. Integrates with Amazon Affiliates for product links and uses AI to assist with content creation.",
    tech: [
      "Next.js 13 App Router",
      "TypeScript",
      "Tailwind CSS",
      "Prisma ORM",
      "MDX for Posts",
      "gray-matter",
      "OpenAI API Integration",
      "SEO Optimization",
      "Static Site Generation (SSG)",
      "Dynamic Metadata",
      "Affiliate Links (Amazon)",
      "Vercel Deployment",
    ],
    image: "/images/projects/project1.png",
    video: "/videos/DavidstechReviews.mp4",
    demo: "https://davidstechreviews.vercel.app/",
    github: "https://github.com/DavidZeff1/davidstechreviews",
  },
  {
    title: "Prisma Clone",
    description:
      "A recreation of the Prisma homepage to practice frontend development. Demonstrates the ability to replicate professional website designs with clean code.",
    tech: [
      "Next.js 13 App Router",
      "TypeScript",
      "Tailwind CSS",
      "Responsive Design",
      "Static Assets & Icons",
      "Vercel Deployment",
    ],
    image: "/images/projects/project1.png",
    video: "/videos/prisma-clone.mp4",
    demo: "https://prisma-clone-steel.vercel.app/",
    github: "https://github.com/DavidZeff1/prisma-clone",
  },

  {
    title: "Survivor Guy (Unity Game)",
    description:
      "A 2D survival game where players fight off waves of enemies and manage resources. Built with Unity and demonstrates core game development patterns and architecture.",
    tech: [
      "Unity Engine",
      "C#",
      "2D Game Development",
      "Object-Oriented Programming (OOP)",
      "Design Patterns (Singleton, Observer, Factory)",
      "Game Loop Architecture",
      "Sprite & Asset Integration",
      "itch.io Deployment",
    ],
    image: "/images/projects/project1.png",
    video: "/videos/survivor-guy.mp4",
    demo: "https://gamerdave141592.itch.io/survivor-guy",
    github: "https://github.com/DavidZeff1/Final-Project",
  },
];
