export const projects = [
  {
    title: "Real-Time Battle Tracker",
    description:
      "A distributed system for live military unit monitoring and tactical analysis. Features real-time position tracking, threat visualization with danger zones, movement trails, and an auto-generated activity feed. Built with event-driven microservices architecture.",
    tech: [
      "React",
      "TypeScript",
      "Redux Toolkit",
      "Leaflet Maps",
      "Node.js",
      "Express",
      "Apache Kafka",
      "Server-Sent Events (SSE)",
      "Docker",
      "Docker Compose",
      "Microservices Architecture",
      "Event-Driven Design",
      "Pub/Sub Messaging",
      "Real-Time Data Streaming",
    ],
    image: "/images/projects/project1.png",
    video: "/videos/BattleTracker.mov",
    demo: "https://github.com/DavidZeff1/battletracker", // add if deployed
    github: "https://github.com/DavidZeff1/battletracker", // update with your actual repo
  },
  {
    title: "David Teaches Code",
    description:
      "A portfolio website showcasing coding tutorials, projects, and technical articles. Features video previews, smooth animations, and a clean, modern design.",
    tech: [
      "Next.js 13 App Router",
      "TypeScript",
      "Tailwind CSS",
      "Framer Motion",
      "React Hooks",
      "Server Components",
      "Vercel Deployment",
      "Responsive Design",
      "Lucide Icons",
    ],
    image: "/images/projects/project1.png",
    video: "/videos/david-teaches-code-preview.mp4",
    demo: "https://david-teaches-code.vercel.app/",
    github: "https://github.com/DavidZeff1/david-teaches-code",
  },
  {
    title: "PlacePal (Airbnb Clone)",
    description:
      "A property rental platform where users can browse listings, book accommodations, and make secure payments. Includes user authentication and a responsive booking interface.",
    tech: [
      "React",
      "Next.js",
      "TypeScript",
      "Node.js",
      "Express-style API",
      "Postgres (Neon)",
      "Prisma ORM",
      "NextAuth Authentication",
      "Stripe Payments",
      "Cloudinary Image Uploads",
      "Tailwind CSS",
      "Vercel Deployment",
      "Responsive UI/UX",
      "Date Range Picker",
    ],
    image: "/images/projects/project1.png",
    video: "/videos/PlacePal.mp4",
    demo: "https://airbnb-83oc.vercel.app/",
    github: "https://github.com/DavidZeff1/airbnb",
  },

  {
    title: "Survivor Guy (Unity Game)",
    description:
      "A 2D survival game where players fight off waves of enemies and manage resources. Built with Unity and demonstrates core game development patterns and architecture.",
    tech: [
      "Unity Engine",
      "C#",
      "2D Game Development",
      "Object-Oriented Programming (OOP)",
      "Design Patterns (Singleton, Observer, Factory)",
      "Game Loop Architecture",
      "Sprite & Asset Integration",
      "itch.io Deployment",
    ],
    image: "/images/projects/project1.png",
    video: "/videos/survivor-guy.mp4",
    demo: "https://gamerdave141592.itch.io/survivor-guy",
    github: "https://github.com/DavidZeff1/Final-Project",
  },
  {
    title: "Algorithm Visualizer",
    description:
      "A web-based tool for interactively visualizing and understanding common sorting and searching algorithms. Built with pure TypeScript, HTML, and CSS, prioritizing clean code and a modular architecture.",
    tech: [
      "TypeScript",
      "HTML5",
      "CSS3",
      "Clean Code Principles",
      "Clean Architecture (e.g., Separation of Concerns)",
      "DOM Manipulation",
      "Asynchronous Programming (e.g., Async/Await for step-by-step visualization)",
      "Event Management",
      "CSS Animations & Transitions",
    ],
    image: "/images/projects/project1.png",
    video: "/videos/AlgoVisualizer.mp4",
    demo: "https://vercel.com/davids-projects-f91907cd/algorithm-visualizer",
    github: "https://github.com/DavidZeff1/algorithm-visualizer",
  },
];
